export interface BoardPin {
  id: string;
  name: string;
  type: 'digital' | 'analog' | 'pwm' | 'power' | 'ground' | 'i2c' | 'spi' | 'uart';
  voltage: string;
  description: string;
}

export interface BoardDefinition {
  id: string;
  name: string;
  family: 'arduino' | 'esp32' | 'raspberry_pi_pico' | 'raspberry_pi';
  category: 'microcontroller' | 'single_board_computer';
  mcu: string;
  flashSize: string;
  operatingVoltage: string;
  clockSpeed: string;
  supportedLanguages: ('arduino_c' | 'micropython' | 'python' | 'c_cpp' | 'blocks')[];
  defaultBaudRate: number;
  availablePins: BoardPin[];
  features: string[];
}

export const BOARD_REGISTRY: Record<string, BoardDefinition> = {
  arduino_uno: {
    id: 'arduino_uno',
    name: 'Arduino Uno R3',
    family: 'arduino',
    category: 'microcontroller',
    mcu: 'ATmega328P',
    flashSize: '32 KB',
    operatingVoltage: '5V',
    clockSpeed: '16 MHz',
    supportedLanguages: ['arduino_c', 'blocks'],
    defaultBaudRate: 9600,
    features: ['14 Digital I/O', '6 Analog Inputs', '6 PWM Channels', 'I2C/SPI/UART'],
    availablePins: [
      { id: '0', name: 'D0 (RX)', type: 'uart', voltage: '5V', description: 'Serial Receive' },
      { id: '1', name: 'D1 (TX)', type: 'uart', voltage: '5V', description: 'Serial Transmit' },
      { id: '2', name: 'D2', type: 'digital', voltage: '5V', description: 'Digital I/O / INT0' },
      { id: '3', name: 'D3 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM / INT1' },
      { id: '4', name: 'D4', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '5', name: 'D5 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '6', name: 'D6 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '7', name: 'D7', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '8', name: 'D8', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '9', name: 'D9 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '10', name: 'D10 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM / SPI SS' },
      { id: '11', name: 'D11 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM / SPI MOSI' },
      { id: '12', name: 'D12', type: 'digital', voltage: '5V', description: 'Digital I/O / SPI MISO' },
      { id: '13', name: 'D13', type: 'digital', voltage: '5V', description: 'Digital I/O / Built-in LED / SPI SCK' },
      { id: 'A0', name: 'A0', type: 'analog', voltage: '5V', description: '10-bit Analog Input' },
      { id: 'A1', name: 'A1', type: 'analog', voltage: '5V', description: '10-bit Analog Input' },
      { id: 'A2', name: 'A2', type: 'analog', voltage: '5V', description: '10-bit Analog Input' },
      { id: 'A3', name: 'A3', type: 'analog', voltage: '5V', description: '10-bit Analog Input' },
      { id: 'A4', name: 'A4 (SDA)', type: 'i2c', voltage: '5V', description: 'Analog Input / I2C Data' },
      { id: 'A5', name: 'A5 (SCL)', type: 'i2c', voltage: '5V', description: 'Analog Input / I2C Clock' },
      { id: '5V', name: '5V', type: 'power', voltage: '5V', description: 'Regulated 5V Power Output' },
      { id: '3V3', name: '3.3V', type: 'power', voltage: '3.3V', description: 'Regulated 3.3V Power Output' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'System Ground Rail' },
    ],
  },
  arduino_nano: {
    id: 'arduino_nano',
    name: 'Arduino Nano V3',
    family: 'arduino',
    category: 'microcontroller',
    mcu: 'ATmega328P',
    flashSize: '32 KB',
    operatingVoltage: '5V',
    clockSpeed: '16 MHz',
    supportedLanguages: ['arduino_c', 'blocks'],
    defaultBaudRate: 9600,
    features: ['Breadboard-Friendly Form Factor', '8 Analog Inputs', '6 PWM', 'Mini-USB'],
    availablePins: [
      { id: '2', name: 'D2', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '3', name: 'D3 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '4', name: 'D4', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '5', name: 'D5 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '6', name: 'D6 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '7', name: 'D7', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '8', name: 'D8', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '9', name: 'D9 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '10', name: 'D10 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '11', name: 'D11 (~)', type: 'pwm', voltage: '5V', description: 'Digital I/O / PWM' },
      { id: '12', name: 'D12', type: 'digital', voltage: '5V', description: 'Digital I/O' },
      { id: '13', name: 'D13', type: 'digital', voltage: '5V', description: 'Built-in LED / SCK' },
      { id: 'A0', name: 'A0', type: 'analog', voltage: '5V', description: 'Analog Input' },
      { id: 'A1', name: 'A1', type: 'analog', voltage: '5V', description: 'Analog Input' },
      { id: 'A4', name: 'A4 (SDA)', type: 'i2c', voltage: '5V', description: 'I2C Data' },
      { id: 'A5', name: 'A5 (SCL)', type: 'i2c', voltage: '5V', description: 'I2C Clock' },
      { id: '5V', name: '5V', type: 'power', voltage: '5V', description: '5V Power' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'Ground' },
    ],
  },
  arduino_mega: {
    id: 'arduino_mega',
    name: 'Arduino Mega 2560',
    family: 'arduino',
    category: 'microcontroller',
    mcu: 'ATmega2560',
    flashSize: '256 KB',
    operatingVoltage: '5V',
    clockSpeed: '16 MHz',
    supportedLanguages: ['arduino_c', 'blocks'],
    defaultBaudRate: 9600,
    features: ['54 Digital I/O', '16 Analog Inputs', '15 PWM', '4 Hardware Serial UARTs'],
    availablePins: [
      { id: '2', name: 'D2 (~)', type: 'pwm', voltage: '5V', description: 'PWM / INT' },
      { id: '3', name: 'D3 (~)', type: 'pwm', voltage: '5V', description: 'PWM / INT' },
      { id: '4', name: 'D4 (~)', type: 'pwm', voltage: '5V', description: 'PWM' },
      { id: '5', name: 'D5 (~)', type: 'pwm', voltage: '5V', description: 'PWM' },
      { id: '13', name: 'D13', type: 'digital', voltage: '5V', description: 'Built-in LED' },
      { id: '20', name: 'D20 (SDA)', type: 'i2c', voltage: '5V', description: 'I2C Data' },
      { id: '21', name: 'D21 (SCL)', type: 'i2c', voltage: '5V', description: 'I2C Clock' },
      { id: 'A0', name: 'A0', type: 'analog', voltage: '5V', description: 'Analog Input' },
      { id: 'A1', name: 'A1', type: 'analog', voltage: '5V', description: 'Analog Input' },
      { id: '5V', name: '5V', type: 'power', voltage: '5V', description: '5V Power' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'Ground' },
    ],
  },
  esp32: {
    id: 'esp32',
    name: 'ESP32 DevKit V1 (WROOM-32)',
    family: 'esp32',
    category: 'microcontroller',
    mcu: 'Xtensa Dual-Core 32-bit LX6',
    flashSize: '4 MB',
    operatingVoltage: '3.3V',
    clockSpeed: '240 MHz',
    supportedLanguages: ['arduino_c', 'micropython', 'blocks'],
    defaultBaudRate: 115200,
    features: ['Wi-Fi 802.11 b/g/n', 'Bluetooth 4.2 BLE', '16 PWM Channels', '12-bit ADC', 'Capacitive Touch'],
    availablePins: [
      { id: '2', name: 'GPIO 2', type: 'digital', voltage: '3.3V', description: 'Built-in Blue LED / Touch2' },
      { id: '4', name: 'GPIO 4', type: 'digital', voltage: '3.3V', description: 'Digital I/O / Touch0 / ADC2_CH0' },
      { id: '5', name: 'GPIO 5', type: 'digital', voltage: '3.3V', description: 'Digital I/O / VSPI CS' },
      { id: '12', name: 'GPIO 12', type: 'digital', voltage: '3.3V', description: 'Digital I/O / Touch5' },
      { id: '13', name: 'GPIO 13', type: 'digital', voltage: '3.3V', description: 'Digital I/O / Touch4' },
      { id: '14', name: 'GPIO 14', type: 'digital', voltage: '3.3V', description: 'Digital I/O / Touch6' },
      { id: '15', name: 'GPIO 15', type: 'digital', voltage: '3.3V', description: 'Digital I/O / Touch3' },
      { id: '18', name: 'GPIO 18', type: 'digital', voltage: '3.3V', description: 'Digital I/O / VSPI SCK' },
      { id: '19', name: 'GPIO 19', type: 'digital', voltage: '3.3V', description: 'Digital I/O / VSPI MISO' },
      { id: '21', name: 'GPIO 21 (SDA)', type: 'i2c', voltage: '3.3V', description: 'I2C Data Line' },
      { id: '22', name: 'GPIO 22 (SCL)', type: 'i2c', voltage: '3.3V', description: 'I2C Clock Line' },
      { id: '23', name: 'GPIO 23', type: 'digital', voltage: '3.3V', description: 'Digital I/O / VSPI MOSI' },
      { id: '34', name: 'GPIO 34 (ADC1)', type: 'analog', voltage: '3.3V', description: 'Input Only 12-bit ADC' },
      { id: '35', name: 'GPIO 35 (ADC1)', type: 'analog', voltage: '3.3V', description: 'Input Only 12-bit ADC' },
      { id: '36', name: 'GPIO 36 (VP)', type: 'analog', voltage: '3.3V', description: 'Sensor VP / ADC1_CH0' },
      { id: '39', name: 'GPIO 39 (VN)', type: 'analog', voltage: '3.3V', description: 'Sensor VN / ADC1_CH3' },
      { id: '3V3', name: '3V3', type: 'power', voltage: '3.3V', description: 'Regulated 3.3V Output' },
      { id: 'VIN', name: 'VIN (5V)', type: 'power', voltage: '5V', description: '5V USB Input/Output' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'Ground Rail' },
    ],
  },
  esp32_c3: {
    id: 'esp32_c3',
    name: 'ESP32-C3 RISC-V DevKit',
    family: 'esp32',
    category: 'microcontroller',
    mcu: 'Single-Core 32-bit RISC-V',
    flashSize: '4 MB',
    operatingVoltage: '3.3V',
    clockSpeed: '160 MHz',
    supportedLanguages: ['arduino_c', 'micropython', 'blocks'],
    defaultBaudRate: 115200,
    features: ['Open-Source RISC-V Architecture', 'Wi-Fi 4 + BLE 5.0', 'Ultra-Low Power', 'USB-Serial-JTAG'],
    availablePins: [
      { id: '2', name: 'GPIO 2', type: 'digital', voltage: '3.3V', description: 'Digital I/O' },
      { id: '3', name: 'GPIO 3', type: 'analog', voltage: '3.3V', description: 'ADC1_CH3' },
      { id: '4', name: 'GPIO 4', type: 'analog', voltage: '3.3V', description: 'ADC1_CH4' },
      { id: '8', name: 'GPIO 8 (RGB LED)', type: 'digital', voltage: '3.3V', description: 'Onboard Addressable RGB' },
      { id: '9', name: 'GPIO 9 (Boot)', type: 'digital', voltage: '3.3V', description: 'Boot Button / I/O' },
      { id: '3V3', name: '3V3', type: 'power', voltage: '3.3V', description: '3.3V Power' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'Ground' },
    ],
  },
  rp2040_pico: {
    id: 'rp2040_pico',
    name: 'Raspberry Pi Pico (RP2040)',
    family: 'raspberry_pi_pico',
    category: 'microcontroller',
    mcu: 'Dual ARM Cortex-M0+',
    flashSize: '2 MB',
    operatingVoltage: '3.3V',
    clockSpeed: '133 MHz',
    supportedLanguages: ['micropython', 'arduino_c', 'blocks'],
    defaultBaudRate: 115200,
    features: ['Dual ARM Cortex M0+', '264 KB SRAM', '8 Programmable I/O (PIO)', '12-bit ADC', 'MicroPython / C/C++'],
    availablePins: [
      { id: 'GP0', name: 'GP0 (UART0 TX)', type: 'uart', voltage: '3.3V', description: 'UART0 Transmit / I2C0 SDA' },
      { id: 'GP1', name: 'GP1 (UART0 RX)', type: 'uart', voltage: '3.3V', description: 'UART0 Receive / I2C0 SCL' },
      { id: 'GP2', name: 'GP2', type: 'digital', voltage: '3.3V', description: 'Digital I/O / SPI0 SCK' },
      { id: 'GP3', name: 'GP3', type: 'digital', voltage: '3.3V', description: 'Digital I/O / SPI0 TX' },
      { id: 'GP4', name: 'GP4 (I2C0 SDA)', type: 'i2c', voltage: '3.3V', description: 'I2C0 Data' },
      { id: 'GP5', name: 'GP5 (I2C0 SCL)', type: 'i2c', voltage: '3.3V', description: 'I2C0 Clock' },
      { id: 'GP14', name: 'GP14', type: 'digital', voltage: '3.3V', description: 'Digital I/O' },
      { id: 'GP15', name: 'GP15', type: 'digital', voltage: '3.3V', description: 'Digital I/O' },
      { id: 'GP25', name: 'GP25 (LED)', type: 'digital', voltage: '3.3V', description: 'Onboard Green LED' },
      { id: 'GP26', name: 'GP26 (ADC0)', type: 'analog', voltage: '3.3V', description: '12-bit Analog Input ADC0' },
      { id: 'GP27', name: 'GP27 (ADC1)', type: 'analog', voltage: '3.3V', description: '12-bit Analog Input ADC1' },
      { id: 'GP28', name: 'GP28 (ADC2)', type: 'analog', voltage: '3.3V', description: '12-bit Analog Input ADC2' },
      { id: '3V3', name: '3V3(OUT)', type: 'power', voltage: '3.3V', description: '3.3V Regulated Output' },
      { id: 'VSYS', name: 'VSYS', type: 'power', voltage: '5V', description: 'System Input Voltage' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'Ground' },
    ],
  },
  rp2040_pico_w: {
    id: 'rp2040_pico_w',
    name: 'Raspberry Pi Pico W',
    family: 'raspberry_pi_pico',
    category: 'microcontroller',
    mcu: 'Dual ARM Cortex-M0+ & CYW43439',
    flashSize: '2 MB',
    operatingVoltage: '3.3V',
    clockSpeed: '133 MHz',
    supportedLanguages: ['micropython', 'arduino_c', 'blocks'],
    defaultBaudRate: 115200,
    features: ['Wi-Fi 802.11n 2.4GHz', 'Bluetooth 5.2', '8 Programmable I/O (PIO)', '264 KB SRAM'],
    availablePins: [
      { id: 'GP0', name: 'GP0 (TX)', type: 'uart', voltage: '3.3V', description: 'UART0 Transmit' },
      { id: 'GP1', name: 'GP1 (RX)', type: 'uart', voltage: '3.3V', description: 'UART0 Receive' },
      { id: 'GP2', name: 'GP2', type: 'digital', voltage: '3.3V', description: 'Digital I/O' },
      { id: 'GP4', name: 'GP4 (SDA)', type: 'i2c', voltage: '3.3V', description: 'I2C Data' },
      { id: 'GP5', name: 'GP5 (SCL)', type: 'i2c', voltage: '3.3V', description: 'I2C Clock' },
      { id: 'GP26', name: 'GP26 (ADC0)', type: 'analog', voltage: '3.3V', description: 'Analog Input ADC0' },
      { id: '3V3', name: '3V3', type: 'power', voltage: '3.3V', description: '3.3V Output' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'Ground' },
    ],
  },
  raspberry_pi: {
    id: 'raspberry_pi',
    name: 'Raspberry Pi 4 / 5 (Linux SBC)',
    family: 'raspberry_pi',
    category: 'single_board_computer',
    mcu: 'Quad-Core 64-bit ARM Cortex-A72 / A76 (Linux OS)',
    flashSize: 'MicroSD / NVMe (32GB - 128GB)',
    operatingVoltage: '3.3V (Logic) / 5V (USB-C)',
    clockSpeed: '1.8 GHz - 2.4 GHz',
    supportedLanguages: ['python', 'c_cpp'],
    defaultBaudRate: 115200,
    features: [
      'Linux Operating System (Raspberry Pi OS)',
      'Python (RPi.GPIO / gpiozero)',
      'Standard Linux C/C++ (libgpiod)',
      '40-Pin Extended GPIO Header',
      'Dual 4K Micro-HDMI & Gigabit Ethernet',
    ],
    availablePins: [
      { id: 'GPIO2', name: 'GPIO 2 (SDA1)', type: 'i2c', voltage: '3.3V', description: 'I2C Data Line / Pin 3' },
      { id: 'GPIO3', name: 'GPIO 3 (SCL1)', type: 'i2c', voltage: '3.3V', description: 'I2C Clock Line / Pin 5' },
      { id: 'GPIO4', name: 'GPIO 4 (GPCLK0)', type: 'digital', voltage: '3.3V', description: 'General Purpose Clock / Pin 7' },
      { id: 'GPIO14', name: 'GPIO 14 (TXD0)', type: 'uart', voltage: '3.3V', description: 'UART Transmit / Pin 8' },
      { id: 'GPIO15', name: 'GPIO 15 (RXD0)', type: 'uart', voltage: '3.3V', description: 'UART Receive / Pin 10' },
      { id: 'GPIO17', name: 'GPIO 17', type: 'digital', voltage: '3.3V', description: 'General Purpose I/O / Pin 11' },
      { id: 'GPIO18', name: 'GPIO 18 (PWM0)', type: 'pwm', voltage: '3.3V', description: 'Hardware PWM / Pin 12' },
      { id: 'GPIO27', name: 'GPIO 27', type: 'digital', voltage: '3.3V', description: 'General Purpose I/O / Pin 13' },
      { id: 'GPIO22', name: 'GPIO 22', type: 'digital', voltage: '3.3V', description: 'General Purpose I/O / Pin 15' },
      { id: 'GPIO23', name: 'GPIO 23', type: 'digital', voltage: '3.3V', description: 'General Purpose I/O / Pin 16' },
      { id: 'GPIO24', name: 'GPIO 24', type: 'digital', voltage: '3.3V', description: 'General Purpose I/O / Pin 18' },
      { id: 'GPIO10', name: 'GPIO 10 (MOSI)', type: 'spi', voltage: '3.3V', description: 'SPI0 Master Out / Pin 19' },
      { id: 'GPIO9', name: 'GPIO 9 (MISO)', type: 'spi', voltage: '3.3V', description: 'SPI0 Master In / Pin 21' },
      { id: 'GPIO11', name: 'GPIO 11 (SCLK)', type: 'spi', voltage: '3.3V', description: 'SPI0 Clock / Pin 23' },
      { id: 'GPIO25', name: 'GPIO 25', type: 'digital', voltage: '3.3V', description: 'General Purpose I/O / Pin 22' },
      { id: '3V3', name: '3.3V Power', type: 'power', voltage: '3.3V', description: 'Pin 1 / Pin 17' },
      { id: '5V', name: '5V Power', type: 'power', voltage: '5V', description: 'Pin 2 / Pin 4' },
      { id: 'GND', name: 'GND', type: 'ground', voltage: '0V', description: 'System Ground (Pin 6, 9, 14, 20, 25)' },
    ],
  },
};
